#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it, but you know that bash, ksh, or zsh is available, you may
#       specify which one to use by setting the SHELL environment variable or
#       by uncommenting the appropriate line below.
#
#   (2) Runs this script from the directory where the Gradle build script is located.
#
#   (3) Arguments to this script are passed to Gradle.
#
#   (4) You are in the working directory of Gradle startup script, so if you don't have a
#       Gradle in this path, all you have to do is download Gradle from https://gradle.org
#
#   (5) For MingW or Cygwin, switch line endings of this file from DOS to Unix before running it:
#       * For MingW write: unix2dos gradlew
#       * For Cygwin write: dos2unix gradlew
#
#   (6) Linux Bash might report wrong cwd on some matchers when using wildcards or brace expansion
#       Precompile the build script has changed recently, which is what this script tries to detect.
#
#   (7) Older Gradle versions (< 2.14) stop the daemon from some reason.
#       Check the status of the daemon by running from the root of the project "gradle --status" or view the java process in the system monitor.
#       If the daemon is stopped by the time you call gradle again, the daemon will be restarted for you.
#   (8) Gradle daemon expiration time is set to 120000 ms (default is 10800000 ms).
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a softlink
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    link=$(expr "$PRG" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(dirname "$PRG")"/$link"
    fi
done
SAVED="$(cd "$(dirname "$PRG")" >/dev/null 2>&1 && pwd)"

# when this wscript is executed as a shell script, it may not have extensions
# and may produce a broken classpath in the absence of :classpath_separator
#
# Even when this wscript is sourced this way, the current directory and the
# variables supplied with this wscript are guaranteed to be set correctly by
# __scriptname.
#

# Try to locate java in the user's PATH, otherwise set JAVA_HOME in your shell/environment.
# On Linux:
# export JAVA_HOME=/usr/lib/jvm/java-<version>-openjdk/

if ! type java >/dev/null 2>&1; then
    echo "WARNING: Could not find 'java' executable. Add Java to your PATH or set JAVA_HOME."
fi

# Increase the maximum file descriptors if we can,
# otherwise fallback to the default provided by the OS.

MAX_FD="maximum"

warn() {
    echo "$*" >&2
}

die() {
    echo
    echo "$*" >&2
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can,
# otherwise fallback to the default provided by the OS.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $MAX_FD_LIMIT != 'unlimited' ] ; then
        MAX_FD=$(expr $MAX_FD_LIMIT / 10)
    fi
    if [ $MAX_FD -lt 8 ] ; then
        MAX_FD=8
    fi
    ulimit -n $MAX_FD
fi

# Escape application args
save() {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}
APP_ARGS=$(save "$@")

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

exec "$JAVACMD" "$@"
