# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true

# Kotlin code style for this project: "official" or "obsolete".
kotlin.code.style=official

# AndroidX package structure
android.useAndroidX=true

# Non-transitive R classes for smaller, faster builds
android.nonTransitiveRClass=true
